#*******************************************************************************
# Ansible Inventory Control File
#
# Purpose:  Defines cluster membership and node roles for Ansible playbooks.
#           Edit hostnames to match your cluster nodes.
#
# NOTE:     Each hostname listed here must have a matching file in host_vars/.
#
# Ref: https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html
#
# Author:
#   Emily D. Carpenter
#   Anderson College of Business and Computing, Regis University
#   MSDS 696/S71: Data Science Practicum II
#   Dr. Douglas Hart, Dr. Kellen Sorauf
#   Practicum II, February-May 2026
#*******************************************************************************

[all]
platinum ansible_connection=local
nickel
zinc
copper
iron
tungsten

# This is the primary cluster controller, add only ONE host in this section
[control]
platinum ansible_connection=local